
# TODO: which config to inherit
base: ""

# TODO: add customized data model, unit or facility definitions, will be combined with builtin ones.
#core:
#  data: "xxx"
#  units: "xxx"
#  facilities: "xxx"

# world definitions
world:
  # how many ticks to ask for an action.
  action_steps: 1

  # sku list in this world
  # this list do not contains price, cost or other facility related attributes,
  # but just base info, like name, id, bom
  skus:
    - id: 1
      name: "sku1"
      output_units_per_lot: 1
      # bill of material that used produce current sku, empty means do not need source material
      bom:
        # key is the source sku name, value is quantity needed to use per time to produce current sku
        sku3: 10
    - id: 2
      name: "sku2"
      output_units_per_lot: 1
    - id: 3
      name: "sku3"
      output_units_per_lot: 1

  # facilities in this world
  facilities:
    - name: "Supplier3" # name of the facility
      class: "SupplierFacility" # class alias of this facility
      # config of this facility
      configs:
        # sku list of this facility
        skus:
          sku3: # sku name and attributes needed for this facility
            init_in_stock: 100
            production_rate: 200
            delay_order_penalty: 10
            type: "production" # production means this is the output production of this facility
            cost": 10
            price": 10
        # config for units
        # config of storage unit
        storage:
          # config of data model of this unit
          data:
            # other config or storage unit
            capacity: 20000
            unit_storage_cost: 10
        distribution:
          data:
            unit_price: 10
        transports:
          # definition of each vehicle
          - class: "TransportUnit"
            data:
              patient: 100
          - class: "TransportUnit"
            data:
              patient: 100
    - name: "Supplier1"
      class: "SupplierFacility"
      configs:
        skus:
          sku1:
            init_in_stock: 100
            production_rate: 200
            delay_order_penalty: 10
            type: "production"
            cost: 10
            price: 100
          sku3:
            init_in_stock: 100
            production_rate: 200
            delay_order_penalty: 10
            type: "material"
            cost: 10
            price: 100
        storage:
          data:
            capacity: 20000
            unit_storage_cost: 10
        distribution:
          data:
            unit_price: 10
        transports:
          - class: "TransportUnit"
            data:
              patient: 100
          - class: "TransportUnit"
            data:
              patient: 100
    - name: "Warehouse1"
      class: "WarehouseFacility"
      configs:
        skus:
          sku1:
            init_stock: 1000
            delay_order_penalty: 10
            price: 100
          sku2:
            init_stock: 1000
            delay_order_penalty: 10
            price: 100
          sku3:
            init_stock: 1000
            delay_order_penalty: 10
            price: 100
        storage:
          data:
            capacity: 20000
            unit_storage_cost: 10
        distribution:
          data:
            unit_price: 10
        transports:
          - class: "TransportUnit"
            data:
              patient: 100
          - class: "TransportUnit"
            data:
              patient: 100
    - name: "ChaoShiFa01"
      class: "RetailerFacility"
      configs:
        skus:
          sku1:
            price: 300
            cost: 10
            init_in_stock: 100
            sale_gamma: 100
          sku3:
            price: 200
            cost: 10
            init_in_stock: 100
            sale_gamma: 100
          sku2:
            price: 100
            cost: 10
            init_in_stock: 100
            sale_gamma: 100
        storage:
          data:
            capacity: 20000
            unit_storage_cost: 10

  # topology used to specify the up/downstream for facilities
  # we split it from facility, so that we can support configuration inherit to override it
  # for a new topology
  # TODO: change the name?
  topology:
    # key is current facility, value if upstream facilities that will provide a certain sku
    Supplier1:
      # this config means "Supplier1" will purchase "sku3" from facility "Supplier3",
      # or any other facility in the list
      sku3:
        - "Supplier3"
    Warehouse1:
      sku1:
        - "Supplier1"
      sku3:
        - "Supplier3"
    ChaoShiFa01:
      sku1:
        - "Supplier1"
      sku3:
        - "Supplier3"

  # map grid definitions
  grid:
    size: [ 20, 20 ]
    # facility position in grid
    facilities:
      Supplier1: [ 0, 0 ]  # (x, y)
      Supplier3: [ 3, 3 ]
      Warehouse1: [ 6, 6 ]
    # cells that un-traversable
    blocks:
      # TODO: later we can have different cell have different travel cost
      railroad:
        - [ 10, 10 ]
        - [ 10, 11 ]
        - [ 10, 12 ]
        - [ 11, 12 ]
