# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

agent:
  model:
    hidden_dims:
      - 16
      - 8
    activation: 
    softmax: false
    batch_norm: true
    skip_connection: false
    head: true
    dropout_p: 0.0
  optimization:
    optim_cls: rmsprop
    optim_params:
      lr: 0.001
  hyper_params: 
    reward_discount: .0
    experience_memory_size: 50000
    experience_memory_overwrite_type: random
    min_experiences: 10
    train_iters: 10
    batch_size: 128
    loss_cls: smooth_l1
    target_update_freq: 5
    tau: 0.1
    double: false
training: 
  env: 
    scenario: supply_chain
    topology: sample1
    durations: 200
  max_episode: 10
  learning_interval: 45 
  exploration:
    parameter_names:
      - epsilon
    start: 0.4
    end: 0.0
distributed:
  group: sc-dqn
  num_actors: 2
  redis_host: localhost
  redis_port: 6379
  learner_update_trigger: 2
  replay_sync_interval: 30
